package com.contacts.kuehne;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Application startup: Spring autogenerated class
 */
@SpringBootApplication
public class ContactListKuehneBackendApplication {

    public static void main(String[] args) {
        SpringApplication.run(ContactListKuehneBackendApplication.class, args);
    }

}
